include_guard(GLOBAL)
find_package(Python3 3.10 COMPONENTS Interpreter REQUIRED)
get_filename_component(FORGEEFX_SDK_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

function(forgeefx_macos_platform output)
    # Explicit target architectures take precedence over the build machine.
    if("${CMAKE_OSX_ARCHITECTURES}" MATCHES "arm64" AND "${CMAKE_OSX_ARCHITECTURES}" MATCHES "x86_64")
        set(platform macos-universal)
    elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
        set(platform macos-arm64)
    elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64")
        set(platform macos-x64)
    elseif(NOT "${CMAKE_OSX_ARCHITECTURES}" STREQUAL "")
        message(FATAL_ERROR "Unsupported Mac block target architectures: ${CMAKE_OSX_ARCHITECTURES}")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
        set(platform macos-arm64)
    else()
        set(platform macos-x64)
    endif()
    set(${output} "${platform}" PARENT_SCOPE)
endfunction()

function(forgeefx_add_block target folder)
    cmake_parse_arguments(BLOCK "" "DEVELOPER;OUTPUT_DIRECTORY" "INCLUDE_DIRECTORIES" ${ARGN})
    if(NOT BLOCK_DEVELOPER)
        message(FATAL_ERROR "forgeefx_add_block requires DEVELOPER")
    endif()
    if(NOT BLOCK_OUTPUT_DIRECTORY)
        set(BLOCK_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/dist")
    endif()
    get_filename_component(folder "${folder}" ABSOLUTE)
    set(generated "${CMAKE_CURRENT_BINARY_DIR}/generated/${target}")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${FORGEEFX_SDK_DIR}/tools/generate_package.py"
        "${folder}" "${generated}" --developer "${BLOCK_DEVELOPER}" COMMAND_ERROR_IS_FATAL ANY)
    file(READ "${generated}/manifest.json" manifest)
    string(JSON effect_id GET "${manifest}" effect_id)
    set(sources "${folder}/dsp.c" "${generated}/descriptor.c")
    if(EXISTS "${folder}/ui.c")
        list(APPEND sources "${folder}/ui.c" "${FORGEEFX_SDK_DIR}/src/render_bridge.c")
    endif()
    add_library(${target} MODULE ${sources})
    target_compile_features(${target} PRIVATE c_std_11)
    target_compile_definitions(${target} PRIVATE FORGEEFX_BUILD_MODULE=1)
    target_include_directories(${target} PRIVATE "${FORGEEFX_SDK_DIR}/include" ${BLOCK_INCLUDE_DIRECTORIES})
    set_target_properties(${target} PROPERTIES PREFIX "" OUTPUT_NAME block ARCHIVE_OUTPUT_NAME ${target} C_VISIBILITY_PRESET hidden)
    if(MSVC)
        target_compile_options(${target} PRIVATE "/FI${FORGEEFX_SDK_DIR}/include/host_dsp.h")
        set_property(TARGET ${target} PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    else()
        target_compile_options(${target} PRIVATE -include "${FORGEEFX_SDK_DIR}/include/host_dsp.h" -fwrapv)
        target_link_libraries(${target} PRIVATE m)
    endif()
    if(WIN32)
        if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR CMAKE_SYSTEM_PROCESSOR MATCHES "ARM|arm")
            message(FATAL_ERROR "ABI v1 Windows package builds currently require x64")
        endif()
        set(platform windows-x64)
    elseif(APPLE)
        set_property(TARGET ${target} PROPERTY SUFFIX ".dylib")
        forgeefx_macos_platform(platform)
    else()
        set(platform linux-${CMAKE_SYSTEM_PROCESSOR})
    endif()
    set(package "${BLOCK_OUTPUT_DIRECTORY}/${effect_id}.fxblock")
    foreach(config IN ITEMS "" DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
        if(config)
            set(suffix "_${config}")
        else()
            set(suffix "")
        endif()
        set_target_properties(${target} PROPERTIES "LIBRARY_OUTPUT_DIRECTORY${suffix}" "${package}/bin/${platform}"
            "RUNTIME_OUTPUT_DIRECTORY${suffix}" "${package}/bin/${platform}")
    endforeach()
    file(MAKE_DIRECTORY "${package}")
    configure_file("${generated}/manifest.json" "${package}/manifest.json" COPYONLY)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${folder}/parameters.json" "${FORGEEFX_SDK_DIR}/tools/generate_package.py")
    if(TARGET forgeefx_block_validator)
        add_test(NAME package_${target} COMMAND forgeefx_block_validator "$<TARGET_FILE:${target}>")
    endif()
endfunction()
